### ISSUE TITLE
add the seperate translation for the razorpay module

### ISSUE THREAD

**Issue by naresh-webkul** [wontone18/razorpay-payment-gateway-bagisto-laravel#2]
hi,
there is no need to copy paste the translation code  when you can add the separate translation.

'key-id'            => 'Key Id',
 'key-secret'    => 'Key Secret',

add these in module's lang/en/app.php file

Thanks!

**Comment by wontone18** [comment]
hi

well if you want to create a form then use a standard structure config/system.php
for language like error, notification use a language. (If you follow laravel package structure)
